# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        12.0

# Monochromatic colors
foreground              #ffffff
background              #121212
selection_foreground    #121212
selection_background    #ffffff

# Cursor
cursor                  #ffffff
cursor_text_color       #121212

# URL underline color when hovering
url_color               #ffffff

# Window borders
active_border_color     #ffffff
inactive_border_color   #333333
bell_border_color       #ffffff

# Tab bar
active_tab_foreground   #121212
active_tab_background   #ffffff
inactive_tab_foreground #888888
inactive_tab_background #1c1c1c
tab_bar_edge            bottom

# Black
color0  #1c1c1c
color8  #333333
# Red
color1  #3a3a3a
color9  #555555
# Green
color2  #5c5c5c
color10 #777777
# Yellow
color3  #7c7c7c
color11 #9e9e9e
# Blue
color4  #9e9e9e
color12 #bdbdbd
# Magenta
color5  #bdbdbd
color13 #d9d9d9
# Cyan
color6  #d9d9d9
color14 #f2f2f2
# White
color7  #e5e5e5
color15 #ffffff


# Window
background_opacity      0.97
window_padding_width    12
confirm_os_window_close 0

# Misc
enable_audio_bell       no
visual_bell_duration    0.0
remember_window_size    yes

# Keybindings for universal copy/paste
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard